version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qw_qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    # volumes:
    #   - ./qdrant_storage:/qdrant/storage
    networks:
      - appnet

  backend:
    build: .
    container_name: qw_backend
    restart: unless-stopped
    ports:
      - "3378:3378"
    depends_on:
      - qdrant
    networks:
      - appnet
      - f_net

networks:
  f_net:
    external: true
    name: docker_f_net
  appnet:
    driver: bridge

